### ISSUE TITLE
Attempting to use "recreatedata" on a specific template causes null error in SimpleTextTemplate.php

### ISSUE THREAD

**Issue by shawndouglas** [samwilson/mediawiki-simpletext#15]
URL in question: https://melodiesofmy.life/Template:Ident?action=recreatedata

Generates "[Xj79RY@4uP6063u-X38IoQAAAAA] /Template:Ident?action=recreatedata Error from line 24 of /home/lostraven/melodiesofmy.life/skins/SimpleText/includes/SimpleTextTemplate.php: Call to a member function getText() on null"

As it turns out, I don't need this template, but Sam suggested there may be a bug in SimpleTextTemplate.php.

**Comment by shawndouglas** [comment]
Ah, looks like you already touched the file a couple of days ago. That's what I get for not looking.

**Comment by samwilson** [comment]
Thanks for reporting the issue though! But yep, I fixed it after you mentioned it in chat. I'm sure there are  more bugs. :)
